# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    rate_limiter:
        public_map_view_limiter:
            policy: 'sliding_window'
            limit: 60
            interval: '1 minute'
        public_map_search_limiter:
            policy: 'sliding_window'
            limit: 120
            interval: '1 minute'
        public_map_detail_limiter:
            policy: 'sliding_window'
            limit: 90
            interval: '1 minute'
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
