nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin:
            - 'http://localhost:5173'
            - 'http://127.0.0.1:5173'
            - 'https://coachat.fr'
            - 'https://la-carte.coachat.fr'
            - 'https://lakarte.fr'
            - 'https://www.lakarte.fr'
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin', 'X-Requested-With']
        allow_credentials: true
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            allow_origin:
                - 'http://localhost:5173'
                - 'http://127.0.0.1:5173'
                - 'https://coachat.fr'
                - 'https://la-carte.coachat.fr'
                - 'https://lakarte.fr'
                - 'https://www.lakarte.fr'
            allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin', 'X-Requested-With']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_credentials: true
            expose_headers: ['Link']
            max_age: 3600
